displayName: geo-fil
type: middleware

import: github.com/eterline/geo-filt
summary: IP based client filter. Uses v2ray geoip.dat files.

iconPath: ""
bannerPath: ""

testData:
  enabled: true
  header_ip: false
  response: 
    content: "<h1>Forbidden: not allowed IP</h1>"
  interceptors:
    - type: "local"
      tag: "allow local IPs"
    - type: "ipset"
      tag: "allow some network IPs"
      invert: false # true|false
      cidrs: ["1.1.0.0/16"]
      addrs: ["8.8.8.8"]
    - type: "ip2counrty"
      tag: "allow russian IPs"
      ip_type: "v4" # v4|v6|all
      invert: false # true|false
      base: "./dataset/IPLocate/ip-to-country-20251224.csv"
      codes: ["RU"]