displayName: GeoFilt
type: middleware

import: github.com/eterline/geo-filt
summary: IP based client filter. Uses v2ray geoip.dat files.

iconPath: ""
bannerPath: ""

testData:
  enabled: true
  geoFile: "/etc/traefik/plugins/github.com/eterline/geo-filt/geoip.dat"
  tags:
    - "ru"
  defined:
    - "10.192.0.0/24"
  allowPrivate: true