displayName: GeoFilt
type: middleware

import: github.com/eterline/geo-filt
summary: IP based client filter. Uses v2ray geoip.dat files.

iconPath: ""
bannerPath: ""

testData:
  enabled: true
  allowPrivate: true
  geoFile: "/etc/traefik/plugins/github.com/eterline/geo-filt/IPLocate-Country-GeoIPCompat-Blocks-IPv4.csv"
  codeFile: "/etc/traefik/plugins/github.com/eterline/geo-filt/IPLocate-Country-GeoIPCompat-Locations-en.csv"
  tags:
    - "ru"
  defined:
    - "10.192.0.0/24"